name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Check Terraform formatting
        run: terraform fmt -check

      - name: Validate terraform
        run: terraform validate

      - name: Init Terraform
        run: terraform init
        
      - name: TPeroerraform plan
        run: terraform plan
